export const getTheme = (isDarkMode) =>
  isDarkMode
    ? {
        background: 'from-slate-900 via-slate-800 via-slate-900',
        bg: 'bg-slate-900',
        surface: 'bg-slate-800',
        cardSurface: 'bg-slate-700',
        text: 'text-slate-100',
        textMuted: 'text-slate-400',
        border: 'border-slate-700',
        accent: 'bg-blue-600',
        accentHover: 'hover:bg-blue-700',
        cardHover: 'hover:bg-slate-600',
        codeArea: 'bg-slate-950',
        gradient: 'from-blue-600 to-indigo-600',
        gradientHover: 'hover:from-blue-700 hover:to-indigo-700',
        folderGradient: 'from-slate-800 to-slate-700',
        borderGradient: 'border-slate-600',
        hoverScale: 'hover:scale-105',
        shadow: 'shadow-slate-800/20',
        shadowLg: 'shadow-lg shadow-slate-800/20',
        dropdownBg: 'bg-slate-800',
        dropdownHover: 'hover:bg-slate-700',
        input: 'bg-slate-800 border-slate-600',
        inputFocus: 'focus:border-blue-500 focus:bg-slate-750',
        overlay: "bg-black/20 backdrop-blur-sm",
      }
    : {
        background: 'from-blue-100 via-indigo-50 to-purple-100',
        bg: 'bg-gray-50',
        surface: 'bg-white',
        cardSurface: 'bg-white',
        text: 'text-gray-900',
        textMuted: 'text-gray-600',
        border: 'border-gray-200',
        accent: 'bg-blue-600',
        accentHover: 'hover:bg-blue-700',
        cardHover: 'hover:bg-gray-50',
        codeArea: 'bg-gray-50',
        gradient: 'from-blue-600 to-indigo-600',
        gradientHover: 'from-blue-700 to-indigo-700',
        folderGradient: 'from-gray-50 to-gray-100',
        borderGradient: 'border-gray-300',
        hoverScale: 'hover:scale-105',
        shadow: 'shadow-gray-200',
        shadowLg: 'shadow-lg shadow-gray-200',
        dropdownBg: 'bg-white',
        dropdownHover: 'hover:bg-gray-50',
        input: 'bg-white border-gray-300',
        inputFocus: 'focus:border-blue-500 focus:bg-white',
        overlay: "bg-black/60 backdrop-blur-sm",
      };